"""
Lexical Analysis

This script investigates the lexical features of the human and model-generated data 
based on multiple linguistic complexity/diversity metrics. 

The aim of this part of the analysis is to answer RQ1:
RQ1: Lexical features 
How lexically similar are responses generated by generic and fine-tuned LLMs compared to human therapist 
responses, based on quantitative measures of lexical richness and complexity?

What the script does: 
1. loads the merged dataset (final_df.csv)
2. computes per-row descriptive metrics using spaCy:
- word count
- Sentence count
- Average sentence length 
- Type-Token Ratio (TTR)
- Corrected Type-Token Ratio (CTTR)
- Measure of Textual Lexical Diversity (MTLD)
3. Produced both per-row analysis files and aggregated summary statistics. 
4. Saves a lexical summary file for reporting. 

Input: final_df.csv  
Intermediate output: lexical_analysis.csv
Final output: lexical_summary.csv

"""


''' -------------------- Setup -------------------- '''

# Load required packages
import spacy
import pandas as pd
import numpy as np
import math
from tqdm import tqdm

# Load spaCy English model (used for tokenization, sentences, etc.)
nlp = spacy.load("en_core_web_sm")

# Enable progress bars for pandas .apply()
tqdm.pandas()

# Input and output paths
FINAL_DF_PATH = "/work/NLP2025/data/final_df.csv"
LEXICAL_ANALYSIS_PATH = "/work/NLP2025/data/lexical_analysis.csv"
LEXICAL_SUMMARY_PATH = "/work/NLP2025/output/lexical_summary.csv"

# Load the merged dataset
df = pd.read_csv(FINAL_DF_PATH)

# Columns for lexical analysis
TEXT_COLS = ["Context", "Human_response", "FT_response", "GPT_response"]


''' ---------------------------- Defining functions -----------------------------'''

# --- Word count ---
def spacy_word_count(text):
    """Count alphabetic tokens using spaCy (ignores punctuation, numbers, etc.)."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text)
    return sum(1 for token in doc if token.is_alpha)

# --- Sentence count ---
def sentence_count(text):
    """Return number of sentences detected by spaCy."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text)
    return len(list(doc.sents))

# --- Average sentence length (words per sentence) ---
def avg_sentence_length(text):
    """Compute average words per sentence using alphabetic tokens only."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text)
    sentences = list(doc.sents)
    if len(sentences) == 0:
        return 0

    # total number of words across sentences
    total_words = sum(len([t for t in sent if t.is_alpha]) for sent in sentences)
    return total_words / len(sentences)

# ---- Type–Token Ratio (TTR) ----
def ttr_spacy(text):
    """Compute Type-Token Ratio: unique words / total words (lowercased)."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text.lower()) # lowercase so 'Hello' and 'hello' count as the same type
    tokens = [t.text for t in doc if t.is_alpha]
    if len(tokens) == 0:
        return 0
    return len(set(tokens)) / len(tokens)

# ---- Corrected TTR (CTTR) ----
def cttr_spacy(text):
    """
    Compute Corrected Type-Token Ratio:
        CTTR = types / sqrt(2 * tokens)
    This normalizes TTR to make it less sensitive to text length.
    """
    if not isinstance(text, str) or text.strip() == "":
        return 0.0
    doc = nlp(text.lower())
    tokens = [t.text for t in doc if t.is_alpha] # alphabetic "words" only
    n_tokens = len(tokens)
    if n_tokens == 0:
        return 0.0
    n_types = len(set(tokens))
    return n_types / math.sqrt(2 * n_tokens)

# ---- MTLD helper functions: this computes MTLD for one direction of text ----
def mtld_calc(tokens, ttr_threshold=0.72, min_segment=10):
    """
    Compute MTLD (Measure of Textual Lexical Diversity) for a token sequence.
    Based on the standard algortihm: thus, it segments the text whenever TTR falls below the threshold.
    THUS, Longer segments → higher lexical diversity.

    """
    if len(tokens) == 0:
        return 0.0

    factors = 0
    types = set()
    token_count = 0

    for tok in tokens:
        token_count += 1
        types.add(tok)
        current_ttr = len(types) / token_count

        # Start a new segment when TTR falls below the threshold
        if token_count >= min_segment and current_ttr <= ttr_threshold:
            factors += 1
            types = set()
            token_count = 0

    # Add partial final segment
    if token_count != 0:
        factors += (1 - (len(types) / token_count - ttr_threshold) /
                    (1 - ttr_threshold))

    if factors == 0:
        return 0.0

    return len(tokens) / factors


# ---- MTLD using spaCy tokenization ----
def mtld_spacy(text, ttr_threshold=0.72, min_segment=10):
    """
    Compute MTLD using alphabetic tokens.
    Returns the mean of forward and backward MTLD values.
    """
    if not isinstance(text, str) or text.strip() == "":
        return 0.0
    doc = nlp(text.lower())
    tokens = [t.text for t in doc if t.is_alpha]
    if len(tokens) == 0:
        return 0.0

    mtld_forward = mtld_calc(tokens, ttr_threshold, min_segment)
    mtld_backward = mtld_calc(list(reversed(tokens)), ttr_threshold, min_segment)
    return (mtld_forward + mtld_backward) / 2


''' ------------------------- Main -------------------------- '''
if __name__ == "__main__":
    #------------------ Word counts per row summary -------------------------
    # --- create a new dataframe for lexical analysis ---
    lex_df = pd.DataFrame()
    lex_df["ID"] = df["ID"]

    # --- compute word count per row for each column ---
    for col in TEXT_COLS:
        print(f"Computing word counts for: {col}")
        lex_df[f"{col}_word_count"] = df[col].progress_apply(spacy_word_count)

    # --- save per-row counts ---
    lex_df.to_csv(LEXICAL_ANALYSIS_PATH, index=False)

    # Select only the word-count columns (everything except ID)
    word_count_cols = [col for col in lex_df.columns if col.endswith("_word_count")]

    # Compute summary statistics
    wordcount_summary = pd.DataFrame({
        "Mean": lex_df[word_count_cols].mean(),
        "Min": lex_df[word_count_cols].min(),
        "Max": lex_df[word_count_cols].max(),
        "SD": lex_df[word_count_cols].std()
    }).round(2)

    # ----------- Sentence counts + Average sentence length -------------
    # Create new dataframe to store results                             
    sentence_df = pd.DataFrame()
    sentence_df["ID"] = df["ID"]

    # Compute per-row metrics
    for col in TEXT_COLS:
        print(f"Computing sentence stats for: {col}")
        sentence_df[f"{col}_sentence_count"] = df[col].progress_apply(sentence_count)
        sentence_df[f"{col}_avg_sentence_length"] = df[col].progress_apply(avg_sentence_length)
    # Select the new columns
    metrics = [col for col in sentence_df.columns if col != "ID"]

    # Build summary table
    sentence_summary = pd.DataFrame({
        "Mean": sentence_df[metrics].mean(),
        "Min": sentence_df[metrics].min(),
        "Max": sentence_df[metrics].max(),
        "SD": sentence_df[metrics].std()
    }).round(2)

    # Load your lexical analysis file
    lex = pd.read_csv("/work/NLP2025/data/lexical_analysis.csv")

    # Compute and print the average word count for each column
    for col in word_count_cols:
        avg = lex[col].mean()

    for col in word_count_cols:
        col_min = lex[col].min()
        col_max = lex[col].max()

    # ---------- Type-Token Ratio per row and summary ----------
    ttr_df = pd.DataFrame()
    ttr_df["ID"] = df["ID"]

    for col in TEXT_COLS:
        print(f"Computing TTR for: {col}")
        ttr_df[f"{col}_TTR"] = df[col].progress_apply(ttr_spacy)

    ttr_metrics = [col for col in ttr_df.columns if col.endswith("_TTR")]

    ttr_summary = pd.DataFrame({
        "Mean": ttr_df[ttr_metrics].mean(),
        "Min": ttr_df[ttr_metrics].min(),
        "Max": ttr_df[ttr_metrics].max(),
        "SD": ttr_df[ttr_metrics].std()
    }).round(3)

    # ---------- Corrected Type-Token Ratio per row and summary ----------
    cttr_df = pd.DataFrame()
    cttr_df["ID"] = df["ID"]

    for col in TEXT_COLS:
        print(f"Computing CTTR for: {col}")
        cttr_df[f"{col}_CTTR"] = df[col].progress_apply(cttr_spacy)

    cttr_cols = [c for c in cttr_df.columns if c.endswith("_CTTR")]

    cttr_summary = pd.DataFrame({
        "Mean": cttr_df[cttr_cols].mean(),
        "Min": cttr_df[cttr_cols].min(),
        "Max": cttr_df[cttr_cols].max(),
        "SD": cttr_df[cttr_cols].std()
    }).round(3)

    # ---------- Doing Measure of Textual Lexical Diversity per row + summary --------------
    mtld_df = pd.DataFrame()
    mtld_df["ID"] = df["ID"]

    for col in TEXT_COLS:
        mtld_df[f"{col}_MTLD"] = df[col].apply(mtld_spacy)

    for col in TEXT_COLS:
        print(f"Computing MTLD for: {col}")
        mtld_df[f"{col}_MTLD"] = df[col].progress_apply(mtld_spacy)

    mtld_cols = [c for c in mtld_df.columns if c.endswith("_MTLD")]

    mtld_summary = pd.DataFrame({
        "Mean": mtld_df[mtld_cols].mean(),
        "Min": mtld_df[mtld_cols].min(),
        "Max": mtld_df[mtld_cols].max(),
        "SD": mtld_df[mtld_cols].std()
    }).round(3)


    # --------------- Combine into a single output dataframe ----------------
    lexical_summary = pd.concat(
        [wordcount_summary, sentence_summary, ttr_summary, cttr_summary, mtld_summary],
        axis=0
    )

    # Save to one file
    lexical_summary.to_csv(LEXICAL_SUMMARY_PATH)