"""
Lexical Analysis

This script investigates the lexical features of the data and generates plots to visualize the comparisons.
The aim of this part of the analysis is to answer RQ1:

RQ1: Lexical features 
How lexically similar are responses generated by generic and fine-tuned LLMs compared to human therapist 
responses, based on quantitative measures of lexical richness and complexity?
Goals:
- total number of tokens/words → 
- number of sentences
- average sentence length 
- Type-Token Ratio (TTR) → Unique words / total words


"""

''' Setup '''

# loading packages
import spacy
import pandas as pd
import numpy as np

#load spaCy model
nlp = spacy.load("en_core_web_sm")

# Paths
FINAL_DF_PATH = "/work/NLP2025/data/final_df.csv"
LEXICAL_ANALYSIS_PATH = "/work/NLP2025/data/lexical_analysis.csv"
LEXICAL_SUMMARY_PATH = "/work/NLP2025/output/lexical_summary.csv"
#WORDCOUNT_SUMMARY_PATH = "/work/NLP2025/output/word_count_summary.csv"
#SENTENCE_SUMMARY_PATH = "/work/NLP2025/output/sentence_stats_summary.csv"
#TTR_SUMMARY_PATH = "/work/NLP2025/output/ttr_summary.csv"

# Read file 
df = pd.read_csv(FINAL_DF_PATH)

# columns to be analyzed
TEXT_COLS = ["Context", "Human_response", "FT_response", "GPT_response"]


''' Defining functions '''

# --- word counting function ---
def spacy_word_count(text):
    """Return number of alphabetic tokens (words) in the text using spaCy."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text)
    return sum(1 for token in doc if token.is_alpha)

# --- Total number of sentences and average sentence length ---
def sentence_count(text):
    """Return number of sentences detected by spaCy."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text)
    return len(list(doc.sents))

# --- Calculate average sentence length (i.e. words per sentence) ---
def avg_sentence_length(text):
    """Return avg words per sentence using spaCy alphabetic tokens."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    doc = nlp(text)
    sentences = list(doc.sents)
    if len(sentences) == 0:
        return 0

    # total words across sentences
    total_words = sum(len([t for t in sent if t.is_alpha]) for sent in sentences)
    return total_words / len(sentences)

# ---- Type-Token Ratio (TTR) → Unique words / total words -----
# Define function using spaCy
def ttr_spacy(text):
    """Compute Type–Token Ratio for a text using spaCy alphabetic tokens."""
    if not isinstance(text, str) or text.strip() == "":
        return 0
    
    doc = nlp(text.lower())  # lowercase so 'Hello' and 'hello' count as same type
    tokens = [t.text for t in doc if t.is_alpha]

    if len(tokens) == 0:
        return 0
    
    return len(set(tokens)) / len(tokens)



''' Main '''
if __name__ == "__main__":
    #------------------ Word counts per row summary -------------------------
    # --- create a new dataframe for lexical analysis ---
    lex_df = pd.DataFrame()
    lex_df["ID"] = df["ID"]

    # --- compute word count per row for each column ---
    for col in TEXT_COLS:
        lex_df[f"{col}_word_count"] = df[col].apply(spacy_word_count)

    # --- save per-row counts ---
    lex_df.to_csv(LEXICAL_ANALYSIS_PATH, index=False)

    # Select only the word-count columns (everything except ID)
    word_count_cols = [col for col in lex_df.columns if col.endswith("_word_count")]

    # Compute summary statistics
    wordcount_summary = pd.DataFrame({
        "Mean": lex_df[word_count_cols].mean(),
        "Min": lex_df[word_count_cols].min(),
        "Max": lex_df[word_count_cols].max(),
        "SD": lex_df[word_count_cols].std()
    }).round(2)

    # save summary
    #wordcount_summary.to_csv(WORDCOUNT_SUMMARY_PATH)

    # ----------- Sentence counts + Average sentence length -------------
    # Create new dataframe to store results                             
    sentence_df = pd.DataFrame()
    sentence_df["ID"] = df["ID"]

    # Compute per-row metrics
    for col in TEXT_COLS:
        sentence_df[f"{col}_sentence_count"] = df[col].apply(sentence_count)
        sentence_df[f"{col}_avg_sentence_length"] = df[col].apply(avg_sentence_length)

    # Select the new columns
    metrics = [col for col in sentence_df.columns if col != "ID"]

    # Build summary table
    sentence_summary = pd.DataFrame({
        "Mean": sentence_df[metrics].mean(),
        "Min": sentence_df[metrics].min(),
        "Max": sentence_df[metrics].max(),
        "SD": sentence_df[metrics].std()
    }).round(2)

    # Load your lexical analysis file
    lex = pd.read_csv("/work/NLP2025/data/lexical_analysis.csv")

    # Compute and print the average word count for each column
    for col in word_count_cols:
        avg = lex[col].mean()

    for col in word_count_cols:
        col_min = lex[col].min()
        col_max = lex[col].max()
    
    #sentence_summary.to_csv(SENTENCE_SUMMARY_PATH)

    # ---------- Type-Token Ratio per row and summary ----------
    ttr_df = pd.DataFrame()
    ttr_df["ID"] = df["ID"]

    for col in TEXT_COLS:
        ttr_df[f"{col}_TTR"] = df[col].apply(ttr_spacy)


    ttr_metrics = [col for col in ttr_df.columns if col.endswith("_TTR")]

    ttr_summary = pd.DataFrame({
        "Mean": ttr_df[ttr_metrics].mean(),
        "Min": ttr_df[ttr_metrics].min(),
        "Max": ttr_df[ttr_metrics].max(),
        "SD": ttr_df[ttr_metrics].std()
    }).round(3)

    #ttr_summary.to_csv(TTR_SUMMARY_PATH)

    # --------------- Combine into a single output dataframe ----------------
    lexical_summary = pd.concat(
        [wordcount_summary, sentence_summary, ttr_summary],
        axis=0
    )

    # Save to one file
    lexical_summary.to_csv(LEXICAL_SUMMARY_PATH)